import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

// Next 16: this file replaces middleware.ts. Refreshes the Supabase session
// cookie and gates every app route behind auth, and behind MFA when the
// account has a verified TOTP factor.
export async function proxy(request: NextRequest) {
  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value)
          );
          response = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  // Do not run code between createServerClient and getUser: the refresh
  // happens inside this call.
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const path = request.nextUrl.pathname;
  const isAuthRoute = path === "/login" || path === "/mfa";

  if (!user) {
    if (!isAuthRoute) {
      const url = request.nextUrl.clone();
      url.pathname = "/login";
      url.search = "";
      return NextResponse.redirect(url);
    }
    return response;
  }

  // MFA gate: if a verified TOTP factor exists, require an aal2 session
  const { data: aal } =
    await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
  const needsMfa =
    aal !== null &&
    aal.nextLevel === "aal2" &&
    aal.nextLevel !== aal.currentLevel;

  if (needsMfa && path !== "/mfa") {
    const url = request.nextUrl.clone();
    url.pathname = "/mfa";
    url.search = "";
    return NextResponse.redirect(url);
  }

  if (!needsMfa && isAuthRoute) {
    const url = request.nextUrl.clone();
    url.pathname = "/today";
    url.search = "";
    return NextResponse.redirect(url);
  }

  if (path === "/") {
    const url = request.nextUrl.clone();
    url.pathname = "/today";
    return NextResponse.redirect(url);
  }

  return response;
}

export const config = {
  matcher: [
    // Everything except static assets, the service worker, manifest and
    // icons. icon.svg and apple-icon.png are generated by the App Router
    // from app/, so they sit at the root and must be excluded by name or
    // the browser gets a redirect to /login instead of a favicon.
    "/((?!_next/static|_next/image|favicon\\.ico|icon\\.svg|apple-icon\\.png|sw\\.js|manifest\\.webmanifest|robots\\.txt|icons/|offline).*)",
  ],
};
